repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: markdown-link-check
      - id: packer-validate
      - id: shellcheck
      - id: terragrunt-hclfmt